import type { Metadata } from "next";

import "../globals.css";
import HomeNav from "@/components/HomeNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <HomeNav />
      {children}
    </div>
  );
}
